jobs:
- job:


  pool:
    vmImage: ubuntu-latest
  displayName: Build

steps:

#Compilar
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Build

#- task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'Sonarcloud'
#    organization: 'tomascastrogon'
#    projectKey: 'TomasCastroGon_springpet-clinic'
#    projectName: 'springpet-clinic'
#  displayName: 'SonarCloud Prepare'

#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'
#    tasks: 'sonarqube'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    sonarQubeRunAnalysis: true
#    sqGradlePluginVersionChoice: 'specify'
#    sonarQubeGradlePluginVersion: '3.5.0.2730'
#    spotBugsAnalysis: false

#Login con Docker
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    command: 'login'

#Build con imagen
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'tomascastrogonzalez/spring-clinic'
    command: 'build'
    Dockerfile: '**/Dockerfile'

#Push
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'tomascastrogonzalez/spring-clinic'
    command: 'push'

#Agregar job
- job:
    pool: 'default'
    step:
- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    command: 'create'
    arguments: 'deployment springclinic --image=tomascastrogonzalez/spring-clinic:26'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


